### ISSUE TITLE
question: next-method-p

### ISSUE THREAD

**Issue by jimka2001** [camsaul/methodical#42]
I see in the README documentation the function `next-method` which apparently corresponds to CLOS `call-next-method`.  Is there a function corresponding to CLOS `next-method-p` ?   How can I know programmatically whether it is legal to call `next-method` ?

**Comment by tekacs** [comment]
From the docs:

> If you're not sure whether a next-method exists, you can check whether it's nil before calling it.

https://github.com/camsaul/methodical#calling-the-next-most-specific-method-with-next-method

**Comment by jimka2001** [comment]
Is there an error in the link you pasted? It doesn't lead to anything interesting in the docs.

**Comment by camsaul** [comment]
@jimka2001 that exact sentence is in the docs in the linked section
